apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.appName.pv.name }}
spec:
  capacity:
    storage: {{ .Values.storagecapacity }}
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  nfs:
    server: 100.0.0.10
    path: "/var/nfs/public"