apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.appName.db.name }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storagecapacity }}
