apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.appName.pv.name }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: {{ .Values.storagecapacity }}