# Deploying container into a pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName.restapi1.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName.restapi1.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName.restapi1.name }}
    spec:
      containers:
      - name: {{ .Values.appName.restapi1.name }}
        # image: hecrom/myweatherservice:latest
        image: "{{ .Values.appName.restapi1.image.repo }}:{{ .Values.appName.restapi1.image.tag }}"
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName.restapi1.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.appName.restapi1.name }}
  ports:
  - name: {{ .Values.appName.restapi1.name }}
    protocol: TCP
    port: 80
    targetPort: 80
  # - name: myweathergrpc
  #   protocol: TCP
  #   port: 666
  #   targetPort: 666

