apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName.restapi3.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName.restapi3.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName.restapi3.name }}
    spec:
      containers:
      - name: {{ .Values.appName.restapi3.name }}
        # image: hecrom/myweathergatewayservice:latest
        image: "{{ .Values.appName.restapi3.image.repo }}:{{ .Values.appName.restapi3.image.tag }}"
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName.restapi3.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.appName.restapi3.name }}
  ports:
  - name: {{ .Values.appName.restapi3.name }}
    protocol: TCP
    port: 80
    targetPort: 80


