apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName.redis.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName.redis.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName.redis.name }}
    spec:
      containers:
      - name: {{ .Values.appName.redis.name }}
        image: redis:5.0.4
        ports:
        - containerPort: 16379
          name: mw-redis-mgmgt-prt
        - containerPort: 6379
          name: mw-redis-msg-prt
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName.redis.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.appName.redis.name }}
  ports:
  - name: mw-redis-mgmgt-prt
    protocol: TCP
    port: 16379
    targetPort: 16379
  - name: mw-redis-msg-prt
    protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName.redis.name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.appName.redis.name }}
  ports:
  - name: mw-redis-mgmgt-prt
    protocol: TCP
    port: 16379
    targetPort: 16379
  - name: mw-redis-msg-prt
    protocol: TCP
    port: 6379
    targetPort: 6379
