apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName.db.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName.db.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName.db.name }}
    spec:
      securityContext:
        fsGroup: 10001
      containers:
      - name: {{ .Values.appName.db.name }}
        image: mcr.microsoft.com/mssql/server:2017-latest
        ports:
        - containerPort: 1433
        env:
          - name: MYWEATHER_MSSQL_PID
            value: "Express"
          - name: ACCEPT_EULA
            value: "Y"
          - name: "SA_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: mssql
                key: "SA_PASSWORD"
        volumeMounts:
        - mountPath: /var/opt/{{ .Values.appName.db.name }}/data
          name: {{ .Values.appName.db.name }}
      volumes:
      - name: {{ .Values.appName.db.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.appName.db.name }}
          # claimName: {{ .Values.appName.pvname }} # nfs
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName.db.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.appName.db.name }}
  ports:
  - name: {{ .Values.appName.db.name }}
    protocol: TCP
    port: 1433
    targetPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName.db.name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.appName.db.name }}
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433
    