apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName.rbmq.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName.rbmq.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName.rbmq.name }}
    spec:
      containers:
      - name: {{ .Values.appName.rbmq.name }}
        image: rabbitmq:3-management
        ports:
        - containerPort: 15672
          name: mw-rb-mgmgt-prt
        - containerPort: 5672
          name: mw-rbmq-msg-prt
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName.rbmq.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.appName.rbmq.name }}
  ports:
  - name: mw-rb-mgmgt-prt
    protocol: TCP
    port: 15672
    targetPort: 15672
  - name: mw-rbmq-msg-prt
    protocol: TCP
    port: 5672
    targetPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName.rbmq.name }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.appName.rbmq.name }}
  ports:
  - name: mw-rb-mgmgt-prt
    protocol: TCP
    port: 15672
    targetPort: 15672
  - name: mw-rbmq-msg-prt
    protocol: TCP
    port: 5672
    targetPort: 5672
