apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName.restapi1.name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
  - host: myweatherdemo.com
    http:
      paths:
      - path: "/api/companies"
        pathType: Prefix        
        backend:
          service:
            name: {{ .Values.appName.restapi1.name }}
            port: 
              number: 80
